package io.github.lxptechnologies.lxpmini.inference

import io.github.lxptechnologies.lxpmini.tokenizer.ByteTokenizer
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class IncrementalTextDecoderTest {
    private val tokenizer = ByteTokenizer()

    @Test
    fun `waits for a complete UTF-8 character before emitting it`() {
        val decoder = IncrementalTextDecoder(tokenizer)
        val streamed = StringBuilder()

        decoder.accept(tokenizer.tokenIdForByte(0xC3), streamed::append)
        assertThat(streamed).hasToString("")

        decoder.accept(tokenizer.tokenIdForByte(0xA9), streamed::append)
        assertThat(streamed).hasToString("é")
        assertThat(decoder.finish(streamed::append)).isEqualTo("é")
        assertThat(streamed).hasToString("é")
    }

    @Test
    fun `flushes malformed generated bytes with replacement characters`() {
        val generatedTokenIds = intArrayOf(
            243, 131, 164, 74, 139, 127, 248, 146, 3, 133, 17, 31, 223, 74, 238, 77,
            202, 182, 128, 144, 75, 181, 18, 178, 54, 227, 164, 82, 38, 115, 57, 255,
        )
        val decoder = IncrementalTextDecoder(tokenizer)
        val streamed = StringBuilder()

        generatedTokenIds.forEach { decoder.accept(it, streamed::append) }
        val completed = decoder.finish(streamed::append)

        assertThat(completed).contains("�")
        assertThat(streamed).hasToString(completed)
    }
}
